appName : ${applicationName}
elementsPerPage: 10
theme : org.wso2.uuf.sample.theme.default
menu :
  main :
    Home : {link: "", icon: "fw-home"}
    Submenu :
      MenuItem1 : {link: "items"}
errorPages:
  "404": /foundation/error/404
  default: /foundation/error/default